spring:
  application:
    name: demo

  datasource:
    url: jdbc:mariadb://192.168.142.10:3306/won
    driver-class-name: org.mariadb.jdbc.Driver
    username: wonzzu
    password: qwer1234



jpa:


